version: "3"

services: 
  app: 
    build: .
    user: root
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: chown -R 1001:1001 /app
    command: python manage.py runserver 0.0.0.0:8000